var counter = 0;
var Token = {
    number : ++counter,
    ident  : ++counter,
    and    : ++counter,
    or     : ++counter,
    not    : ++counter,
    _for   : ++counter,
    _while : ++counter,
    _if    : ++counter,
    _else  : ++counter,
    l      : ++counter,
    g      : ++counter,
    minus  : ++counter,
    div    : ++counter,
    mul    : ++counter,
    plus   : ++counter,
    equal  : ++counter,
    semi   : ++counter,
    power  : ++counter,
    ob     : ++counter,
    cb     : ++counter,
    fob    : ++counter,
    fcb    : ++counter,
    eq     : ++counter,
    neq    : ++counter,
    ge     : ++counter,
    le     : ++counter,
    uminus : ++counter,
    string : ++counter,
    funct_call: ++counter,
    comma : ++counter,
    eof    : ++counter,
    funct  : ++counter,
    pipe   : ++counter,
    _return : ++counter,
    preinc  : ++counter,
    postinc : ++counter,
    inc     : ++counter,
    dec     : ++counter
};
module.exports = Token;
